### ISSUE TITLE
Feature Request: support diagnostic messages

### ISSUE THREAD

**Issue by igorlfs** [rouge8/neotest-rust#22]
From `:h neotest.diagnostic`

**Comment by rouge8** [comment]
Can you give more details about what you're looking for or you'd expect?

**Comment by igorlfs** [comment]
Sure!

When using neotest with Python, if a test fails, neotest adds a diagnostic pinpointing exactly where the error occurred and why it happened:
![image](https://user-images.githubusercontent.com/84649544/225615341-244222f9-9f9e-4a65-8d26-da1cc249049a.png)
Currently, with rust, there's no such info:
![image](https://user-images.githubusercontent.com/84649544/225615511-97a796e8-c552-4f5b-8b8b-3c0371bfe4e1.png)

**Comment by bram209** [comment]
I can pick this up
