### ISSUE TITLE
Tests with `#[should_panic]` macro are ignored

### ISSUE THREAD

**Issue by morgsmccauley** [rouge8/neotest-rust#29]
Adding the `#[should_panic]` macro, below the `#[test]` macro, to an existing test causes it to be ignored. Replacing the order, i.e. `#[should_panic]` followed by `#[test]` on the next line, seems to work.

This seems to be related to the [treesitter query](https://github.com/rouge8/neotest-rust/blob/main/lua/neotest-rust/init.lua#L111) which looks for the `#[test]` macro on a function. Perhaps it just picks up the first macro defined?

**Comment by rouge8** [comment]
It sounds like you have a workaround, but I'd accept a PR making the query accept `#[test]` followed by `#[should_panic]`.
