### ISSUE TITLE
neotest-rust: ...plenary/context_manager.lua:47: /tmp/nvimXXXXXX/2: No such file or directory

### ISSUE THREAD

**Issue by epigramengineer** [rouge8/neotest-rust#3]
Hi! This project looks super cool and it looks like it's brand new! Super excited to try it out. I've run into an issue when running it, so I thought I'd post here :)

```
❯ rustc --version
rustc 1.62.0
❯ cargo --version
cargo 1.62.0
❯ cargo nextest --version
cargo-nextest 0.9.14
❯ cargo nextest run
   Compiling rust v0.1.0 (/home/tanner/projects/tmp)
    Finished test [unoptimized + debuginfo] target(s) in 0.24s
  Executable unittests src/lib.rs (target/debug/deps/rust-7e43bc118666ed88)
    Starting 1 tests across 1 binaries
        PASS [   0.001s] rust tests::test_thing
     Summary [   0.002s] 1 tests run: 1 passed, 0 skipped
❯ nvim --version
NVIM v0.7.0
```

lib.rs
```
#[cfg(test)]
mod tests {
    #[test]
    fn test_thing() {
        assert!(true)
    }
}
```

Neotest-run command output in neovim:
```
neotest-rust: ...nager/start/plenary-nvim/lua/plenary/context_manager.lua:47: /tmp/nvimU923sF/2: No such file or directory   
```

Running with latest source (as of time of this post) of all:

1. neotest `rev = "2f5e9f634fd66351f323bd3c97eaa82f3dfbcb61"`
1. neotest-rust `rev = "ae9539b4d4a213c08106d830db66795a42337092"`
1. plenary-nvim `rev = "986ad71ae930c7d96e812734540511b4ca838aa2"`

**Comment by rouge8** [comment]
Hmm, a couple questions:

1. What command are you using to run the tests? e.g. `require("neotest").run.run()`, `require("neotest").run.run(vim.fn.expand("%"))`, etc.
3. Could you upload your neotest log? Probably found at `~/.cache/nvim/neotest.log`.

**Comment by rouge8** [comment]
Another thing to try might be updating `cargo-nextest`, the latest version is 0.9.31.

**Comment by epigramengineer** [comment]
Updating cargo-nextest worked. Thanks!
