### ISSUE TITLE
Unable to parse the test

### ISSUE THREAD

**Issue by sramekj** [rouge8/neotest-rust#34]
Hi,

I have this simple test:
![image](https://user-images.githubusercontent.com/14794165/232154401-2e19caab-6e68-485c-8f0d-12ddae81e6ca.png)

And I am getting this error:
![image](https://user-images.githubusercontent.com/14794165/232154358-a43ac2d7-c116-4186-8aae-6ce997be17f8.png)

When I run all the tests for the file it says there are no tests. It seems like it is unable to parse/find my tests.

Also, when I run "cargo nextest r" it passes.

My config:

![image](https://user-images.githubusercontent.com/14794165/232154842-4704bc28-1b22-411e-a9cb-03f90a5ad326.png)

Can you tell me what am I doing wrong?

Thanks!

**Comment by rouge8** [comment]
Can you show the whole test file and it's path? Please use codeblocks instead of screenshots, thanks.

**Comment by sramekj** [comment]
The path is "hello-world\tests\hello-world.rs" (hello-world dir is a project root with cargo.toml etc). The test file contains only the test as its seen on the first screenshot. I am using my nvim on Windows, however the file has LF line endings.

**Comment by rouge8** [comment]
Works fine for me... I don't use Windows, so I'm not sure how much I can help here.

**Comment by sramekj** [comment]
Nevermind, my nextest intallation was corrupted somehow. After installation of pre-builded binaries with `cargo binstall cargo-nextest --secure` it just worked.
