### ISSUE TITLE
Package name should be read from `Cargo.toml`

### ISSUE THREAD

**Issue by bram209** [rouge8/neotest-rust#41]
First of all, thank you for making this!

In my project, I have a workspace with a few crates. These crates have a different (shorter) folder name than their corresponding package names: https://github.com/bram209/leptosfmt/blob/main/formatter/Cargo.toml

Running a test in the formatter crate will result in the following filter expression:
`package(formatter) & test(/^source_file::tests::multiple$/)`

but it should be:
`package(leptosfmt-formatter) & test(/^source_file::tests::multiple$/)`

**Comment by rouge8** [comment]
Interesting. I think we'd have to update https://github.com/rouge8/neotest-rust/blob/e4baa0b02be7a7b9271da0a98eb82fb278a0c1e7/lua/neotest-rust/init.lua#L216-L217 to use `cargo metadata` and parse the output to find the correct package (and its name). I think if we're going to do that, we should start caching the output of `cargo metadata` now that we're calling it repeatedly...

I'm not sure when I'll have time to get to this, but that's how I'd approach it if you want to take a shot!

**Comment by rouge8** [comment]
I added the cache to `cargo metadata`, so all that's left is updating the package name logic (and adding tests).

**Comment by bram209** [comment]
Hi, that approach looks good to me, but would do `cargo read-manifest` instead of `cargo metadata` in this case

**Comment by rouge8** [comment]
Looks like `cargo read-manifest` is deprecated, but `cargo metadata --no-deps` (the replacement) is an improvement!
