### ISSUE TITLE
Failed to run test after recent upgrade.

### ISSUE THREAD

**Issue by tubzby** [rouge8/neotest-rust#45]
```
neotest-rust: ...uzhiping/.local/share/nvim/lazy/neotest/lua/nio/init.lua:105: The coroutine failed with this message:
...share/nvim/lazy/neotest-rust/lua/neotest-rust/errors.lua:7: attempt to index local 'output' (a nil value)
stack traceback:
        ...share/nvim/lazy/neotest-rust/lua/neotest-rust/errors.lua: in function 'parse_errors'
        ...l/share/nvim/lazy/neotest-rust/lua/neotest-rust/init.lua:380: in function 'results'
        ...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:131: in function '_run_spec'
        ...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:89: in function <...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:88>
Press ENTER or type command to continue
```

**Comment by rouge8** [comment]
Can you provide an example that triggers this?

**Comment by tubzby** [comment]
I was running this simple code:

```
#[cfg(test)]
mod tests {
    #[test]
    fn test() {
        let mut i: u8 = 255;
        i += 1;
    }
}
```
For some reason, it works now.

**Comment by tubzby** [comment]
Sorry for the last post, this test fails:

```
#[cfg(test)]
mod tests {
    #[test]
    fn test() {
        let mut i: u8 = 255;
        i = i.wrapping_add(1);
        assert_eq!(i, 0);
    }
}

```

**Comment by rouge8** [comment]
Seems to work for me, running neotest on this `main.rs`:

```rust
fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    #[test]
    fn test() {
        let mut i: u8 = 255;
        i = i.wrapping_add(1);
        assert_eq!(i, 0);
    }
}
```

**Comment by henriquemelicias** [comment]
@tubzby , did you try installing `cargo-nextest` with  `cargo install cargo-nextest --locked`? I was getting the same error but that fixed it.

**Comment by tubzby** [comment]
It works now, I'm not sure what happened, sometimes when I run a test with key bindings, nothing happens, I have to switch to vs code to run the unit test.

Are there any logs that I can look into?

**Comment by Zeioth** [comment]
@rouge8  Same here
![screenshot_2023-08-12_20-18-21_519476446](https://github.com/rouge8/neotest-rust/assets/3357792/21e5bbce-e92f-4d36-b8b2-fd7f582e9d61)

It seems the right command is `cargo test` not `cargo nextest`

**Comment by rouge8** [comment]
> @rouge8 Same here ![screenshot_2023-08-12_20-18-21_519476446](https://user-images.githubusercontent.com/3357792/260251162-21e5bbce-e92f-4d36-b8b2-fd7f582e9d61.png)
> 
> It seems the right command should be `cargo test` not `cargo nextest`

No, that's not correct. As it says in the README, this plugin works with [cargo-nextest](https://nexte.st/).

**Comment by Zeioth** [comment]
yes thank you, doing `cargo install nextest` seems to do the trick
![screenshot_2023-08-12_21-42-39_205460188](https://github.com/rouge8/neotest-rust/assets/3357792/ffe02b67-dad5-4d17-b0f0-f5d1fbd474d4)

**Comment by solc42** [comment]
@rouge8 Hello!

I'v faced the same problem, at least the error I receive is the same as OP, but in my case I found out the reason.

I copied args for initialization from example: 

```
require("neotest").setup({
  adapters = {
    require("neotest-rust") {
        args = { "--no-capture" },
    }
  }
})
```

That lead to cargo launches with args like 

```
cargo nextest run --no-fail-fast --config-file /var/folders/0y/gvl9x07x341fhm6zq23ps9480000gn/T/nvim.coin/ROMNaO/0.nextest.toml --profile neotest --no-capture -E 'test(/^tests::/)'
```

And --no-capture lead to empty system-out/system-err nodes in xml result:

```
        <testcase name="tests::test_ref" classname="lobster-proxy::bin/lobster-proxy" timestamp="2023-08-12T22:26:57.410+00:00" time="0.004">
            <failure type="test failure"/>
            <system-out></system-out>
            <system-err></system-err>
        </testcase>
```

so the input to parse_errors method become nil.

I guarded with simple precheck for nil in local version like:

```
function M.parse_errors(output)
    if output == nil then
        return {}
    end
    local message, line = output:match("thread '[^']+' panicked at '([^']+)', [^:]+:(%d+):%d+")
<...>
```

It really took me a while, cause at the beginning I did know nothing about lua.

PS May be OP has another source of the problem, but i smashed my head a bit, before figuring out. Should I make a PR or it works like that by design?
