### ISSUE TITLE
Tests don't run; 2.junit.xml: No such file or directory

### ISSUE THREAD

**Issue by turboladen** [rouge8/neotest-rust#5]
I'm just giving `neotest` a whirl for the first time, trying it out with some Rust unit tests. I'm on nvim 0.7.2 on macOS 12.5.1.

I have these mappings:

```lua
        vim.keymap.set("n", "<leader>tn", neotest.run.run)
        vim.keymap.set("n", "<leader>tf", "neotest.run.run(vim.fn.expand('%'))")
        vim.keymap.set("n", "<leader>td", "neotest.run.run({strategy = 'dap'})")
```

When I try to run the nearest test, I get: `E486: Pattern not found: float`. Not sure what that means, but seems like it could something with my config. The problem that seems a bit more straightforward is when I try to run tests for the file, I get:

```
neotest-rust: ...acker/start/plenary.nvim/lua/plenary/context_manager.lua:47: /var/folders/k9/xm7wlry90z3fjwl909bs1bb80000gp/T/nvimF2oxR3/2.junit.xml: No such file or directory
```

I see a reference to `junit` [here](https://github.com/rouge8/neotest-rust/blob/5a159bf9b31b1029f5716ecc55120e6e63e5ea42/lua/neotest-rust/init.lua#L119); seems a bit odd to require anything junit for testing rust, no?

**Comment by rouge8** [comment]
What version of cargo-nextest are you using? The junior XML is produced by cargo-nextest and parsed by this plug-in to determine the test results.

**Comment by turboladen** [comment]
Oooh, my bad! I'd read that nextest was _supported_, not required. Sorry about that. 🤦‍♂️
