### ISSUE TITLE
Running a single test fails

### ISSUE THREAD

**Issue by ErezAmihud** [rouge8/neotest-rust#50]
Hello, I have the following file:
```rust
use std::num::ParseIntError;
fn number_sum(data:&str) -> Result<u32, ParseIntError>{ 
    let mut ot = Vec::new();
    for line in data.split("\n"){
        ot.push(line.parse::<u32>()?);
    }
    Ok(ot.iter().sum())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_number_list_sum_ok(){
        assert_eq!(number_sum("323\n392").unwrap(), 323+392);
    }
    #[test]
    fn test_number_list_sum_error(){
        assert!(number_sum("hi\n392").is_err());
    }
}
```

When trying to run only the `test_number_list_sum_error` test (via the neotest sidebar) I get the following error:
```
error: expected expression
   ╭────
 1 │ 'test(/tests::test_number_list_sum_error$/)'
   · ──────────────────────┬─────────────────────
   ·                       ╰── missing expression
   ╰────

  error: expected end of expression
   ╭────
 1 │ 'test(/tests::test_number_list_sum_error$/)'
   · ──────────────────────┬─────────────────────
   ·                       ╰── unparsed input
   ╰────

error: failed to parse filter expression
```
Or in a photo:

![image](https://github.com/rouge8/neotest-rust/assets/63999403/bae78653-ce2c-41d6-8ce3-2650126114f2)

NOTE that when running the entire tests module everything works.

**Comment by rouge8** [comment]
Works for me. Can you provide an example repo that fails? I generated a new project with `cargo new --lib gh50` and replaced `lib.rs` with your sample above and everything was fine.

**Comment by ErezAmihud** [comment]
> Works for me. Can you provide an example repo that fails? I generated a new project with `cargo new --lib gh50` and replaced `lib.rs` with your sample above and everything was fine.

[Here is the example repo](https://github.com/ErezAmihud/gh-50-example)
It appears the problem only happens on windows. On linux it worked just fine.
I have updated all of my plugins (tree sitter and such), and my nvim version is `v0.9.0`.
