### ISSUE TITLE
Test cases from /target folder are extracted unnecessarily

### ISSUE THREAD

**Issue by blaind** [rouge8/neotest-rust#59]
It appears that neotest-rust might mistakenly be extracting test cases from .rs files within the rust-target folder.

Based on the information provided in https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/adapters/interface.lua, the API offers a "filter_dir" method that allows an adapter to exclude specific folders from test cases. Neotest-python, for example, filters out the virtualenv directory "venv," as shown here: https://github.com/nvim-neotest/neotest-python/commit/288e58b83d53f622f0a52612bd567b568a7706d1.

Perhaps neotest-rust should also filter the "target" folder or provide the filter configuration to the user, potentially in a format similar to how neotest-python exposes the "is_test_file" method (see https://github.com/nvim-neotest/neotest-python)

Tested with https://github.com/blaind/webp-animation/ :
![image](https://github.com/rouge8/neotest-rust/assets/1299457/373b1be6-5a02-427f-8aa0-716b8c8a640f)

**Comment by rouge8** [comment]
We should be able to extract the `target_directory` from the `cargo metadata` call we already make and exclude that. I'm currently on vacation, so I'm not likely to get to this soon, but PRs welcome!
