### ISSUE TITLE
Debug fails because `file_path` is nil

### ISSUE THREAD

**Issue by BonaBeavis** [rouge8/neotest-rust#60]
When trying to run a test with:

```lua
require("neotest").run.run_last({ strategy = "dap" })
```

I get:

```
neotest-rust: ...vis/.neovim/bundle/neotest/lua/neotest/lib/file/init.lua:22: attempt to concatenate local
 'file_path' (a nil value)
```

I know this is not much, I do not have rust-tools installed, maybe there is an undocumented dependency.

If it is needed:

```lua
dap.adapters.codelldb = {
    type = 'server',
    port = '${port}',
    executable = {
        -- CHANGE THIS to your path!
        command = '/home/notme/.local/share/nvim/mason/packages/codelldb/codelldb',
        args = { '--port', '${port}' },
    },
}
```

Any pointers where to look?

**Comment by rouge8** [comment]
I’ve never actually used the debug functionality other than testing to verify it worked. @MarkEmmons any ideas?

**Comment by theoribeiro** [comment]
I have rust-tools installed and am also getting the same error when trying to debug a test. They run just fine, debugging is the only issue.

**Comment by MarkEmmons** [comment]
I'll try to take a look in the next week.

**Comment by Frederick888** [comment]
Can you try https://github.com/rouge8/neotest-rust/pull/68? Not really familiar with the treesitter queries and stuff, but fingers crossed it fixes the issue.
